plugins {
    id 'java'
}

dependencies {

    /** =============================================================================
     * Spring Cloud - Start
     ============================================================================= */

    // gateway -------------------------------------------------------
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'

    // eureka-client -------------------------------------------------
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // config-client -------------------------------------------------
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
//    implementation 'org.springframework.cloud:spring-cloud-starter-bus-amqp'

    /** =============================================================================
     * Spring Cloud - End
     ============================================================================= */

    // monitoring
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // jwt --------------------------------------------------------------------------
    implementation 'io.jsonwebtoken:jjwt-gson:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'

//    implementation 'javax.xml.bind:jaxb-api:2.3.1'



}

