# ---------------------------------
# server / application
# ---------------------------------
server:
  port: 8761
  shutdown: graceful

application:
  title: ${spring.application.name}
  version: 1.0.0
  lastdate: 2024-09-03

# ---------------------------------
# spring
# ---------------------------------
spring:
  application:
    name: discovery-service
  lifecycle:
    timeout-per-shutdown-phase: 20s

#logging:
#  config: classpath:log4j2.xml

# ---------------------------------
# eureka
# ---------------------------------
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


---

spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://kubernetes.docker.internal:8763/eureka/
  instance:
    hostname: localhost


---

spring:
  config:
    activate:
      on-profile: eureka3

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: kubernetes.docker.internal
