# ---------------------------------
# server / application
# ---------------------------------
server:
  port: 0
  shutdown: graceful

application:
  title: ${spring.application.name}
  version: 1.0.0
  lastdate: 2024-09-03

# ---------------------------------
# spring
# ---------------------------------
spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
# ---------------------------------
# configuration amqp reload - rabbitmq
# ---------------------------------
#    rabbitmq:
#      host: 127.0.0.1
#      port: 5672
#      username: guest
#      password: guest
#      listener:
#        simple:
#          prefetch: 5

# ---------------------------------
# datasource 정보를 Config Serivce의 order-service.yml 로 이동
# ---------------------------------


# ---------------------------------
# eureka
# ---------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # eureka 서버에 인스턴스를 표시하기 위해
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true


# ---------------------------------
# logging
# ---------------------------------
logging:
  level:
    fbc: info
#  config: classpath:log4j2.xml


