# ---------------------------------
# server / application
# ---------------------------------
server:
  port: 0
  shutdown: graceful

application:
  title: ${spring.application.name}
  version: 1.0.0
  lastdate: 2024-09-03

# ---------------------------------
# spring
# ---------------------------------
spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 20s

  # ---------------------------------
  # Database
  # ---------------------------------
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true #Hibernate 초기화가 먼저 실행되도록 Spring Boot에서 데이터소스 초기화를 지연
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
#    password:

# ---------------------------------
# eureka
# ---------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # eureka 서버에 인스턴스를 표시하기 위해
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true


# ---------------------------------
# logging
# ---------------------------------
logging:
  level:
    fbc: info
#  config: classpath:log4j2.xml


