# ---------------------------------
# server / application
# ---------------------------------
server:
  port: 0
  shutdown: graceful

application:
  title: ${spring.application.name}
  version: 1.0.0
  lastdate: 2024-09-03

# ---------------------------------
# spring
# ---------------------------------
spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
# ---------------------------------
# configuration amqp reload - rabbitmq
# ---------------------------------
#    rabbitmq:
#      host: 127.0.0.1
#      port: 5672
#      username: guest
#      password: guest
#      listener:
#        simple:
#          prefetch: 5

# ---------------------------------
# datasource 정보를 Config Serivce의 order-service.yml 로 이동
# ---------------------------------

  # ---------------------------------
  # zipkin
  # ---------------------------------
  zipkin:
    base-url: http://localhost:9411
    enabled: true

# ---------------------------------
# eureka
# ---------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # eureka 서버에 인스턴스를 표시하기 위해
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# ---------------------------------
# spring actuator
# ---------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, info, metrics, prometheus
  # ---------------------------------
  # spring actuator-zipkin
  # ---------------------------------
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


# ---------------------------------
# logging
# ---------------------------------
logging:
  level:
    fbc: info
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#  config: classpath:log4j2.xml


